# Generated by Django 6.0.4 on 2026-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video (YouTube)')], default='foto', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galeria/')),
                ('url_video', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número = aparece primero')),
            ],
            options={
                'verbose_name': 'Item de galería',
                'verbose_name_plural': 'Galería',
                'ordering': ['orden', '-fecha'],
            },
        ),
    ]
