# Generated by Django 6.0.4 on 2026-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('recurso', 'Recurso educativo'), ('comunidad', 'Comunidad'), ('herramienta', 'Herramienta'), ('documento', 'Documento'), ('otro', 'Otro')], default='recurso', max_length=20)),
                ('icono', models.CharField(blank=True, help_text='Emoji del ícono, ej: 📚', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links y recursos',
                'ordering': ['orden', '-fecha'],
            },
        ),
    ]
