# Generated by Django 6.0.4 on 2026-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('edad', models.CharField(blank=True, choices=[('10-13', '10 – 13 años'), ('14-17', '14 – 17 años'), ('18-22', '18 – 22 años'), ('23+', '23 años o más')], max_length=10)),
                ('programa', models.CharField(blank=True, choices=[('web', 'Programación Web'), ('robotica', 'Robótica e IA'), ('diseno', 'Diseño y Videojuegos'), ('apps', 'Desarrollo de Apps'), ('ciberseguridad', 'Ciberseguridad'), ('datos', 'Ciencia de Datos'), ('asesoria', 'Quiero asesoría')], max_length=20, verbose_name='Programa de interés')),
                ('fuente', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp / amigo'), ('google', 'Google'), ('colegio', 'Colegio / universidad'), ('otro', 'Otro')], max_length=20, verbose_name='¿Cómo nos conoció?')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
